"""initial schema

Revision ID: 2d802ec2e524
Revises: 
Create Date: 2026-06-20 03:46:36.960209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d802ec2e524'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games_master',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('igdb_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('first_release_date', sa.Date(), nullable=True),
    sa.Column('genres', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('game_id'),
    sa.UniqueConstraint('igdb_id')
    )
    with op.batch_alter_table('games_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_master_title'), ['title'], unique=False)

    op.create_table('platforms',
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('platform_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('accounts',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.platform_id'], ),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('platform_id', 'username', name='uq_account_platform_username')
    )
    op.create_table('gfn_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('available_on_steam', sa.Boolean(), nullable=True),
    sa.Column('available_on_epic', sa.Boolean(), nullable=True),
    sa.Column('available_on_gog', sa.Boolean(), nullable=True),
    sa.Column('gfn_deeplink_url', sa.String(length=500), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games_master.game_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id')
    )
    op.create_table('owned_games_epic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('epic_namespace', sa.String(length=100), nullable=True),
    sa.Column('epic_item_id', sa.String(length=100), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games_master.game_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'epic_item_id', name='uq_epic_account_item')
    )
    op.create_table('owned_games_gog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('gog_product_id', sa.String(length=100), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games_master.game_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'gog_product_id', name='uq_gog_account_product')
    )
    op.create_table('owned_games_steam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('steam_appid', sa.Integer(), nullable=False),
    sa.Column('playtime_minutes', sa.Integer(), nullable=True),
    sa.Column('last_played', sa.DateTime(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games_master.game_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'steam_appid', name='uq_steam_account_appid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owned_games_steam')
    op.drop_table('owned_games_gog')
    op.drop_table('owned_games_epic')
    op.drop_table('gfn_games')
    op.drop_table('accounts')
    op.drop_table('platforms')
    with op.batch_alter_table('games_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_master_title'))

    op.drop_table('games_master')
    # ### end Alembic commands ###
